#include "gaia/scene/scene_loader.hpp"

#include "gaia/core/json.hpp"

#include <cmath>
#include <fstream>
#include <limits>
#include <sstream>

namespace gaia {
namespace {
const JsonValue::Object* Object(const JsonValue& value) { return value.AsObject(); }
const JsonValue::Array* Array(const JsonValue& value) { return value.AsArray(); }
const JsonValue* Field(const JsonValue::Object& object, const char* key) { const auto iterator = object.find(key); return iterator == object.end() ? nullptr : &iterator->second; }
Status Number(const JsonValue::Object& object, const char* key, float& output) { const auto* value = Field(object, key); const auto* number = value == nullptr ? nullptr : value->AsNumber(); if (number == nullptr || !std::isfinite(*number) || *number > std::numeric_limits<float>::max() || *number < -std::numeric_limits<float>::max()) return Status::Error(std::string("Expected finite float for '") + key + "'"); output = static_cast<float>(*number); return Status::Ok(); }
Status Text(const JsonValue::Object& object, const char* key, std::string& output) { const auto* value = Field(object, key); const auto* text = value == nullptr ? nullptr : value->AsString(); if (text == nullptr) return Status::Error(std::string("Expected string for '") + key + "'"); output = *text; return Status::Ok(); }
Status Boolean(const JsonValue::Object& object, const char* key, bool& output) { const auto* value = Field(object, key); const auto* boolean = value == nullptr ? nullptr : value->AsBool(); if (boolean == nullptr) return Status::Error(std::string("Expected boolean for '") + key + "'"); output = *boolean; return Status::Ok(); }
Status Vec3(const JsonValue::Object& object, const char* key, std::array<float, 3>& output) { const auto* value = Field(object, key); const auto* array = value == nullptr ? nullptr : value->AsArray(); if (array == nullptr || array->size() != 3) return Status::Error(std::string("Expected 3-number array for '") + key + "'"); for (std::size_t index = 0; index < 3; ++index) { const auto* number = (*array)[index].AsNumber(); if (number == nullptr || !std::isfinite(*number) || *number > std::numeric_limits<float>::max() || *number < -std::numeric_limits<float>::max()) return Status::Error(std::string("Invalid vector for '") + key + "'"); output[index] = static_cast<float>(*number); } return Status::Ok(); }
}
Status SceneLoader::LoadFromFile(const std::string& path, World& world) { std::ifstream input(path, std::ios::binary); if (!input) return Status::Error("Cannot open scene: " + path); std::ostringstream text; text << input.rdbuf(); return LoadFromText(text.str(), world); }
Status SceneLoader::LoadFromText(const std::string& text, World& world) {
    auto document = ParseJson(text); if (!document.IsOk()) return document.GetStatus(); const auto* root = Object(document.Value()); if (root == nullptr) return Status::Error("Scene root must be an object");
    const auto* entitiesValue = document.Value().Find("entities"); const auto* entities = entitiesValue == nullptr ? nullptr : Array(*entitiesValue); if (entities == nullptr) return Status::Error("Scene requires entities array");
    World staged;
    for (const auto& entityValue : *entities) { const auto* entityObject = Object(entityValue); if (entityObject == nullptr) return Status::Error("Entity must be an object"); std::string name; auto status = Text(*entityObject, "name", name); if (!status.IsOk()) return status; auto entity = staged.CreateEntity(name); if (!entity.IsOk()) return entity.GetStatus(); const auto* componentsValue = entityValue.Find("components"); const auto* components = componentsValue == nullptr ? nullptr : Object(*componentsValue); if (components == nullptr) return Status::Error("Entity requires components object");
        if (const auto* transform = componentsValue->Find("transform")) { const auto* data = Object(*transform); if (data == nullptr) return Status::Error("transform must be object"); TransformComponent component; if (!(status = Vec3(*data, "position", component.Position)).IsOk() || !(status = Vec3(*data, "rotationDegrees", component.RotationDegrees)).IsOk() || !(status = Vec3(*data, "scale", component.Scale)).IsOk()) return status; if (!(status = staged.SetTransform(entity.Value(), component)).IsOk()) return status; }
        if (const auto* renderable = componentsValue->Find("renderable")) { const auto* data = Object(*renderable); if (data == nullptr) return Status::Error("renderable must be object"); RenderableComponent component; if (!(status = Text(*data, "mesh", component.Mesh)).IsOk() || !(status = Text(*data, "material", component.Material)).IsOk()) return status; if (!(status = staged.SetRenderable(entity.Value(), std::move(component))).IsOk()) return status; }
        if (const auto* body = componentsValue->Find("rigidBody")) { const auto* data = Object(*body); if (data == nullptr) return Status::Error("rigidBody must be object"); RigidBodyComponent component; if (!(status = Number(*data, "mass", component.Mass)).IsOk() || !(status = Number(*data, "gravityScale", component.GravityScale)).IsOk() || !(status = Number(*data, "atmosphericDensity", component.AtmosphericDensity)).IsOk() || !(status = Number(*data, "viscosity", component.Viscosity)).IsOk()) return status; if (!(status = staged.SetRigidBody(entity.Value(), component)).IsOk()) return status; }
        if (const auto* audio = componentsValue->Find("audioEmitter")) { const auto* data = Object(*audio); if (data == nullptr) return Status::Error("audioEmitter must be object"); AudioEmitterComponent component; if (!(status = Text(*data, "clip", component.Clip)).IsOk() || !(status = Number(*data, "gain", component.Gain)).IsOk() || !(status = Boolean(*data, "loop", component.Loop)).IsOk()) return status; if (!(status = staged.SetAudioEmitter(entity.Value(), std::move(component))).IsOk()) return status; }
        if (const auto* agent = componentsValue->Find("utilityAgent")) { const auto* data = Object(*agent); if (data == nullptr) return Status::Error("utilityAgent must be object"); UtilityAgentComponent component; if (!(status = Number(*data, "energy", component.Energy)).IsOk() || !(status = Number(*data, "temperature", component.Temperature)).IsOk() || !(status = Number(*data, "seekEnergyWeight", component.SeekEnergyWeight)).IsOk() || !(status = Number(*data, "seekShelterWeight", component.SeekShelterWeight)).IsOk()) return status; if (!(status = staged.SetUtilityAgent(entity.Value(), component)).IsOk()) return status; }
        if (const auto* script = componentsValue->Find("script")) { const auto* data = Object(*script); if (data == nullptr) return Status::Error("script must be object"); ScriptComponent component; if (!(status = Text(*data, "script", component.Script)).IsOk()) return status; if (!(status = staged.SetScript(entity.Value(), std::move(component))).IsOk()) return status; }
    } world = std::move(staged); return Status::Ok();
}
} // namespace gaia
